export const HPGETLIST = 'HP-GET-LIST';
export const HPGETLISTDATA = 'HP-GET-LIST-DATA';
export const ACERGETLIST = 'ACER-GET-LIST';
export const ACERGETLISTDATA = 'ACER-GET-LIST-DATA';
export const DELLGETLIST = 'DELL-GET-LIST';
export const DELLGETLISTDATA = 'DELL-GET-LIST-DATA';
export const LENOVOGETLIST = 'LENOVO-GET-LIST';
export const LENOVOGETLISTDATA = 'LENOVO-GET-LIST-DATA'